version: '3'

services:
  air:
    image: cosmtrek/air
    working_dir: /go-bun-chi
    environment:
      - "air_wd=/go-bun-chi"
    container_name: go-bun-chi
    ports:
      - 8081:8081
    volumes:
      - "./:/go-bun-chi"

  dbmysql: 
    image: mysql:8
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: dbmysql
    restart: unless-stopped
    environment:
      - "TZ=Asia/Jakarta"
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=db_bunchi"
      - "MYSQL_USER=dev"
      - "MYSQL_PASSWORD=dev"
      - "MYSQL_INITDB_SKIP_TZINFO=true"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
  
volumes:
  go-bun-chi: